// Display names
export const TICKER_NAMES = {
  // Futures
  'ES1!': 'S&P 500 Futures',
  'NQ1!': 'Nasdaq Futures',
  'RTY1!': 'Russell 2000 Futures',
  'YM1!': 'Dow Jones Futures',
  // DX/VIX
  'DX-Y.NYB': 'US Dollar Index',
  'CBOE:VIX': 'CBOE VIX',
  // Metals
  'GC1!': 'Gold',
  'SI1!': 'Silver',
  'HG1!': 'Copper',
  'PL1!': 'Platinum',
  'PA1!': 'Palladium',
  'ALI1!': 'Aluminum',
  // Commodities
  'CL1!': 'WTI Crude Oil',
  'NG1!': 'Natural Gas',
  // Yields
  'US2Y': '2Y Treasury Yield',
  'US10Y': '10Y Treasury Yield',
  'US30Y': '30Y Treasury Yield',
  // Global
  '^N225': 'Nikkei 225',
  '^KS11': 'KOSPI',
  '^NSEI': 'Nifty 50',
  '000001.SS': 'Shanghai Comp.',
  '000300.SS': 'CSI 300',
  '^HSI': 'Hang Seng',
  '^FTSE': 'FTSE 100',
  '^FCHI': 'CAC 40',
  '^GDAXI': 'DAX',
  // Crypto
  'BTC': 'Bitcoin',
  'ETH': 'Ethereum',
  'SOL': 'Solana',
  'XRP': 'XRP',
  // Major ETFs
  'SPY': 'SPDR S&P 500',
  'QQQ': 'Invesco QQQ',
  'DIA': 'SPDR Dow Jones',
  'IWM': 'iShares Russell 2000',
  // Sub-market
  'IVW': 'iSh S&P 500 Growth',
  'IVE': 'iSh S&P 500 Value',
  'IJK': 'iSh S&P 400 MidCap Growth',
  'IJJ': 'iSh S&P 400 MidCap Value',
  'IJT': 'iSh S&P 600 SmCap Growth',
  'IJS': 'iSh S&P 600 SmCap Value',
  'MGK': 'Vanguard Mega Cap Growth',
  'VUG': 'Vanguard Growth',
  'VTV': 'Vanguard Value',
  // Sectors
  'XLK': 'Technology',
  'XLV': 'Health Care',
  'XLF': 'Financials',
  'XLE': 'Energy',
  'XLY': 'Consumer Discret.',
  'XLI': 'Industrials',
  'XLB': 'Materials',
  'XLU': 'Utilities',
  'XLRE': 'Real Estate',
  'XLC': 'Comm. Services',
  'XLP': 'Consumer Staples',
  // EW Sectors (Invesco style)
  'RYT': 'EW Technology',
  'RYH': 'EW Health Care',
  'RYF': 'EW Financials',
  'RYE': 'EW Energy',
  'RCD': 'EW Consumer Disc.',
  'RGI': 'EW Industrials',
  'RTM': 'EW Materials',
  'RYU': 'EW Utilities',
  'EWRE': 'EW Real Estate',
  'EWCO': 'EW Comm. Services',
  'RHS': 'EW Consumer Stap.',
  // EW Sectors
  'RSPG': 'Energy EW',
  'RSPT': 'Technology EW',
  'RSPF': 'Financials EW',
  'RSPN': 'Industrials EW',
  'RSPD': 'Cons Discr EW',
  'RSP': 'S&P 500 EW',
  'RSPU': 'Utilities EW',
  'RSPM': 'Materials EW',
  'RSPH': 'Health Care EW',
  'RSPR': 'Real Estate EW',
  'RSPS': 'Cons Staples EW',
  'RSPC': 'Comm Svcs EW',
  // Thematic
  'BOTZ': 'Global X AI & Robotics',
  'HACK': 'ETFMG Prime Cybersecurity',
  'SOXX': 'iSh Semiconductor',
  'ICLN': 'iSh Global Clean Energy',
  'SKYY': 'First Trust Cloud Computing',
  'XBI': 'SPDR Biotech',
  'ITA': 'iSh Aerospace & Defense',
  'FINX': 'Global X FinTech',
  'ARKG': 'ARK Genomic Revolution',
  'URA': 'Global X Uranium',
  'AIQ': 'Global X AI & Technology',
  'CIBR': 'First Trust Cybersecurity',
  'ROBO': 'ROBO Global Robotics',
  'ARKK': 'ARK Innovation',
  'DRIV': 'Global X Autonomous & EV',
  'OGIG': "O'Shares Global Internet",
  'ACES': 'ALPS Clean Energy',
  'PAVE': 'Global X U.S. Infrastructure',
  'HERO': 'Global X Video Games & Esports',
  'CLOU': 'Global X Cloud Computing',
  // Country / Region
  'EWJ': 'Japan',
  'EWY': 'South Korea',
  'INDA': 'India',
  'MCHI': 'China',
  'GXC': 'China S&P ETF',
  'EWH': 'Hong Kong',
  'EWU': 'United Kingdom',
  'EWQ': 'France',
  'EWG': 'Germany',
  'EWZ': 'Brazil',
  'EWT': 'Taiwan',
  'EWA': 'Australia',
  'EWC': 'Canada',
  'EWL': 'Switzerland',
  'EWP': 'Spain',
  'EWS': 'Singapore',
  'TUR': 'Turkey',
  'EWM': 'Malaysia',
  'EPHE': 'Philippines',
  'THD': 'Thailand',
  'VNM': 'Vietnam',
  'EWI': 'Italy',
  'EWN': 'Netherlands',
  'EWD': 'Sweden',
  'EWK': 'Belgium',
  'EWO': 'Austria',
  'GREK': 'Greece',
  'ARGT': 'Argentina',
  'EUFN': 'Europe Financials',
  'ECH': 'Chile',
  'IEV': 'Europe',
  'IEUR': 'Core MSCI Europe',
  'EWW': 'Mexico',
  'EZU': 'Eurozone',
  'EEM': 'Emerging Markets',
  'EFA': 'MSCI EAFE',
  'EZA': 'South Africa',
  'ACWI': 'MSCI ACWI',
  'KSA': 'Saudi Arabia',
  'EIDO': 'Indonesia',
}
